
[build]
  command = "npm run install-all && CI=false npm run build"
  functions = "netlify/functions"
  publish = "client/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  CI = "false"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
